version: "3"

services:
  webserver:
    container_name: webserver
    image: php:apache-bullseye
    ports:
      - "80:80/tcp"
    volumes:
      - web-directory:/var/www/html
    restart: unless-stopped

volumes:
  web-directory:
    external: true
