version: "3"

services:
  webserver:
    container_name: webserver
    build: build/.
    image: html-server:1.10
    ports:
      - "80:80/tcp"
    volumes:
      - /bin/systemctl:/bin/systemctl
      - /run/systemd/system:/run/systemd/system
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /sbin/shutdown:/sbin/shutdown
    restart: unless-stopped
