version: "3"

services:
  webserver:
    container_name: webserver
    build: build/.
    image: html-server:1.7
    ports:
      - "80:80/tcp"
    volumes:
      - /bin/systemctl:/bin/systemctl
      - /run/systemd/system:/run/systemd/system
    restart: unless-stopped
